feat: add extraManifest
zabbix-community/helm-zabbix pull request #121
Opened 2024-11-22 08:43 UTC by sinux-l5d

#### What this PR does / why we need it:

This PR adds a extraManifest key. It allows arbitrary deployment of a Kubernetes manifest within the same Helm release.

In our case, we deploy an extra Secret that uses helm-secrets.

#### Which issue this PR fixes
  - fixes #119

#### Special notes for your reviewer:

We've discussed in the issue above about "add[ing] and test[ing] all occurrences of extra parameters like extraEnv". However I don't see the connection between extraEnv and extraManifest: the latter should be added as-is in the release, without modification from other extra parameters.

#### Checklist

- [x] [DCO](https://github.com/zabbix-community/helm-zabbix/blob/master/CONTRIBUTING.md) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2024-11-23 12:43 UTC, fibbs commented
Thanks for this contribution! I will test it!
I feel like a dot-dot-release upgrade would be enough for this PR? So, not raising Chart version to 6.1.0 but to 6.0.2 instead? (.2 because of #123 raising to 6.0.1). @aeciopires what do you think?

2024-11-23 13:52 UTC, aeciopires commented
Hi @sinux-l5d!

Thanks for your contribution. I will review your PR.

Hi @fibbs!

The goal of this PR is to add a new "feature" to the chart, it is not a hotfix. I agree with 6.1.0.

But the publishing of the helm chart is associated with the manually created tag. Using this approach, I can accumulate many PRs and publish all the changes together. That is why I did not add helm docs to the pipeline to avoid conflicts. I had a lot of problems with this last year.

So, during the process of publishing a new release, I evaluate all the changes from the PRs that I will publish, choose the appropriate version number and then publish them in one package...

The explanation for this is that last year I was very busy at work, so several PRs accumulated throughout the year and I published them all in one batch release.

Another reason is that some people who opened the PR were not responding quickly when I had free time (which is normal because everyone's schedule is asynchronous even depending on their interest and free time).

2024-11-23 13:57 UTC, aeciopires requested changes

2024-11-23 13:57 UTC, aeciopires commented on charts/zabbix/Chart.yaml
> +version: 6.1.0 # helm chart version
Hi @sinux-l5d!

Can you remove this version? I will choose the correct number during the publish process.

2024-11-23 13:57 UTC, aeciopires commented on charts/zabbix/README.md
Hi @sinux-l5d!

Can you remove the changes of documentation of this file?

The changes need be done in README.md.gotmpl file.

After this run the make gen-docs command to update content of this README.md automatically.

2024-11-23 13:57 UTC, aeciopires commented on charts/zabbix/artifacthub-pkg.yml
> +version: 6.1.0 # helm chart version
Hi @sinux-l5d!

Can you remove this version? I will choose the correct number during the publish process.

2024-11-25 13:55 UTC, aeciopires approved these changes
Thanks @sinux-l5d!

It`s ok to me!

@fibbs I will let merge with you to solved possible conflict in code with other PRs

2024-11-26 09:02 UTC, merged