Add namespace declaration to manifests
zabbix-community/helm-zabbix pull request #140
Opened 2024-12-24 23:58 UTC by mustdiechik

#### What this PR does / why we need it:

- best practice
- prevent argocd error like "Namespace for $name networking.k8s.io/v1, Kind=Ingress is missing."

2024-12-26 22:16 UTC, fibbs commented
Hey, I do not agree that this is good practice to do. Even more, my understanding of how Helm handles the rendered manifest's `metadata.namespace` is as follows:
> 	•	When you deploy a Helm chart with helm install or helm upgrade, you can specify a namespace using the --namespace flag.
>	•	If you do not specify the --namespace flag, Helm defaults to the default namespace unless overridden in the chart configuration.

The error you are seeing must be originated by anything else in your ArgoCD usage. I am not an ArgoCD expert, as I use with Flux and Fleet in daily manner, but I did deploy several Helm Charts with ArgoCD (specifically developed ones for a customer application, but also an older version of this one) and neither my own ones nor this Zabbix server one did ever need the changes you are suggesting with this PR.

2024-12-26 22:16 UTC, fibbs commented
@aeciopires your thoughts?

2024-12-30 13:57 UTC, aeciopires commented
Hi, @fibbs! 

I think @mustdiechik is right. The PR is not setting the namespace name, it continues to behave as you said, only the name of the chosen namespace is being registered in the YAML.

I'm going to test it here using kind and argocd+github+helm to validate the need for this, but at first it seems to make sense.

I looked at the Prometheus helm chart (which I believe is also widely used with ArgoCD)... and there is this namespace line in the helm chart template files.

References:
* https://artifacthub.io/packages/helm/prometheus-community/prometheus?modal=template&template=cm.yaml
* https://artifacthub.io/packages/helm/prometheus-community/prometheus?modal=template&template=deploy.yaml
* https://artifacthub.io/packages/helm/prometheus-community/prometheus?modal=template&template=headless-svc.yaml
* https://artifacthub.io/packages/helm/prometheus-community/prometheus?modal=template&template=ingress.yaml

2024-12-30 14:04 UTC, aeciopires commented
Thank you @mustdiechik for your contribution.

Can you please remove the changes in the Chart.yaml file?

Only maintainers should change this file just before releasing a release in Helm Chart... We recently changed the process to allow the accumulation of changes and pull requests in the same version. 

Changes in Chart.yaml and README.md files in different PRs were causing a lot of conflict issues in the Git repository.

See new process in [CONTRIBUTING.md](https://github.com/zabbix-community/helm-zabbix/blob/main/CONTRIBUTING.md)

2024-12-30 14:59 UTC, fibbs commented
I am still not convinced this is a good idea. I have read at several places that it is "bad practice" to define the manifest's namespace within the templates and that it would not be necessary, as Helm would take care of that by itself.
I have myself several deployments running in ArgoCD where namespace is not explicitly set in any of the templates. Could I see the `Application` definition from ArgoCD you are using @mustdiechik?

2024-12-30 15:25 UTC, fibbs commented
I have spun up a testcluster, did an installation of ArgoCD and will do some tests, also for #139

2024-12-30 15:55 UTC, aeciopires commented
> I am still not convinced this is a good idea. I have read at several places that it is "bad practice" to define the manifest's namespace within the templates and that it would not be necessary, as Helm would take care of that by itself. I have myself several deployments running in ArgoCD where namespace is not explicitly set in any of the templates. Could I see the `Application` definition from ArgoCD you are using @mustdiechik?

Hi @fibbs. 

It is really bad practice to leave the namespace value fixed. You are right on that point. 

But what I understand in the PR is that the value of the namespace field is dynamic depending on whether Helm and ArgoCD are using it at the installation.

I ran Helm with dry-run manually, and Helm is not really rendering the namespace in the resulting YAML files... I think that is what ArgoCD is complaining about...

I am finishing configuring ArgoCD and I will test it with and without the suggested change... then we will evaluate it with more information.

2024-12-30 16:11 UTC, fibbs commented
![Bildschirmfoto 2024-12-30 um 17 10 56](https://github.com/user-attachments/assets/2c424813-c358-4cb3-b189-fc5333c83811)

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2024-12-30T15:33:01Z"
  generation: 49
  name: zabbix1
  namespace: argocd
  resourceVersion: "1631027"
  uid: 0e313ecc-d9b5-47c8-8938-7dfeecf8768f
spec:
  destination:
    namespace: zabbix1
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: zabbix
    helm:
      parameters:
      - name: ingress.enabled
        value: "true"
      - name: ingress.hosts[0].host
        value: zabbix1.local
      - name: ingress.hosts[0].paths[0].paths
        value: /
      - name: ingress.hosts[0].paths[0].pathType
        value: ImplementationSpecific
      - name: zabbixServer.zabbixServerHA.enabled
        value: "false"
    repoURL: https://zabbix-community.github.io/helm-zabbix
    targetRevision: 6.1.2
```

2024-12-30 16:48 UTC, aeciopires commented
@fibbs I had tha same result.

My application.yaml of the ArgoCD is:

```yaml
# References:
#
# https://blog.argoproj.io/draft-argo-cd-v2-6-release-candidate-ced1853bbfdb
# https://github.com/argoproj/argo-cd/issues/2531
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zabbix
  namespace: argocd
  annotations:
    # https://argo-cd.readthedocs.io/en/stable/user-guide/sync-waves/
    argocd.argoproj.io/sync-wave: "6"
  finalizers:
    # https://argo-cd.readthedocs.io/en/stable/user-guide/app_deletion/
    - resources-finalizer.argocd.argoproj.io
# https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  # https://argo-cd.readthedocs.io/en/release-2.6/user-guide/projects/
  project: default
  # https://argo-cd.readthedocs.io/en/release-2.6/user-guide/multiple_sources/
  sources:
  - repoURL: https://zabbix-community.github.io/helm-zabbix
    chart: zabbix
    targetRevision: 6.1.2
    helm:
      valueFiles:
      - $values/argocd/zabbix/zabbix_values.yaml
  - repoURL: https://gitlab.com/aeciopires/repo-test.git
    # Branch or tag name
    targetRevision: main
    ref: values
  # https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/
    syncOptions:
    - CreateNamespace=true
```

I create a git repository for values. The principal diference is:

I don't used ingress. I test with [MetalLB](https://metallb.io/installation/) using the LoadBalancer service type:

```yaml
[...]

zabbixWeb:
  enabled: true
  ZBX_SERVER_HOST: zabbix-zabbix-server
  ZBX_SERVER_PORT: 10051
  service:
    # Using MetalLB
    type: LoadBalancer
    externalTrafficPolicy: Cluster
    nodePort: 31080
    port: 80
[...]

ingress:
  enabled: false
[...]
```

@mustdiechik can you share more information about your installation?

2025-01-09 00:43 UTC, mustdiechik commented
```
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
```
If you had set "namespace" you will not see argocd error, because argocd would be checking this namespace.
In common approach, I did not set namespace because in one release I install manifests in few namespaces: zbx, network policy, etc.

This PR does not brake your standard machinery, but makes it possible to use in non-standard approaches (CI\CD).

2025-01-09 00:54 UTC, aeciopires commented
Hi @mustdiechik!

Thanks for sharing more information.

We are currently facing an issue on the main branch regarding the deployment of Zabbix with postgresql.

To resolve this, @fibbs is putting a lot of effort into PR #148, which contains a breaking change but definitively solves the issue.

No further PRs will be merged until the new version with the breaking change and fix is ​​released.

After that, we will review other PRs and issues again and release hotfix versions with the necessary fixes and features.

We apologize for the inconvenience and appreciate your understanding.

2025-01-12 14:22 UTC, aeciopires commented
Hi, @fibbs!

Can you please look at this PR again? Do you understand the scenario and agree with the suggestion?

If so, can you please decide whether we wait @mustdiechik to resolve the conflicts before the new release or release the new release and add the solution from this PR as a hotfix later?

2025-01-12 16:39 UTC, aeciopires commented
Hello @mustdiechik!

A new version of this chart has been released.
Can you sync your branch and resolve the conflicts?

2025-01-13 04:37 UTC, mustdiechik commented
> Hello @mustdiechik!
> 
> A new version of this chart has been released. Can you sync your branch and resolve the conflicts?

done

2025-01-13 09:47 UTC, aeciopires commented on charts/zabbix/templates/service.yaml
Hello @mustdiechik!

In this file, we have different services inside if conditional. Can you add the namespace for each one?

2025-01-13 09:55 UTC, aeciopires commented
Hello @mustdiechik 

Can you add the namespace in ``templates/tests/test-server-connection.yaml`` and ``templates/tests/test-web-connection.yaml`` files?

2025-01-13 09:56 UTC, aeciopires requested changes
Hello @mustdiechik!

I made some comments to improve this PR

2025-01-13 10:02 UTC, mustdiechik commented
fixed

2025-01-13 10:05 UTC, aeciopires approved these changes
Thanks @mustdiechik 

I will publish a new release

2025-01-13 10:05 UTC, merged